### ISSUE TITLE
FQDN lists with inBlockList rule example

### ISSUE THREAD

**Issue by msenturk** [homebot/dnswall#1]
Hi, 
Im trying to setup up dnswall with list of known malware domain address that I dowlaned from malwaredomain.com and other similar free osint sites but I couldn't figure it out how to set rule with "inBlockList" which I saw in docs.

Can you provide an example for it please ?

thanks for sharing this tool.

**Comment by ppacher** [comment]
I'm sorry but unfortunately I haven't implemented the inBlocklist feature yet. I didn't had enough time lately but will try to keep working on dnswall as soon as possible (I'm using it locally and already have a list of features I'd like to implement).

If you like, feel free to create a pull request and I'd be happy to merge it. Otherwise I'll try to implement it within the next two weeks if that's enough for you. (I may have some time on the weekend and I guess the blocklist feature shouldn't be that complicated)

cheers

**Comment by ppacher** [comment]
Project will be archived. Please checkout https://github.com/safing/portmaster
